/*
 * Copyright (c) 2019. Phasmid Software
 */

package com.phasmidsoftware.bridge

package object cards {

  /**
    * Transposition-table key: one `Long` per hand (see `State.evaluateKey`/`BitState.evaluateKey`
    * for the bit layout). A dedicated case class rather than a plain `(Long, Long, Long, Long)`
    * tuple, so the four fields stay unboxed `long`s in the generated bytecode -- a generic
    * `TupleN` boxes each field to `Object` regardless of its static type. Profiling
    * (`jfr view hot-methods`/`allocation-by-class` on a `BitAnalysis` search) showed
    * `Tuple4$.apply`/`Product4.productElement` and `java.lang.Long` boxing as measurable, avoidable
    * costs on every transposition-table probe/store -- this key is on that hot path.
    */
  final case class CacheKey(h0: Long, h1: Long, h2: Long, h3: Long)

}
